---
- name: "Laboratorio de Variables"
  hosts: nodos
  vars_files: 
    "vars/default.yml"
  vars:
    grupos_sistema:
      - ctic
      - devops
      - everis
  
  tasks:
    - name: "Instalar servicios"
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ servicios }}"

    - name: "Arrancar servicios"
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ servicios }}"
    
    - name: "Crear los grupos"
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ grupos_sistema }}"

    - name: "Crear el usuario administrador"
      user:
        name: administrador
        groups: "{{ usuarios['administrador']['grupo'] }}"
        generate_ssh_key: "{{ usuarios['administrador']['generar_key'] }}"
        ssh_key_bits: 2048
        ssh_key_file: "{{ usuarios['administrador']['ruta_key'] }}"
        expires: "{{ usuarios['administrador']['expira'] }}"

      - name: "Creacion del usuario everis_prueba"
      user:
        name: everis_prueba
        groups: "{{ usuarios['everis_prueba']['grupo'] }}"
        generate_ssh_key: "{{ usuarios['everis_prueba']['generar_key'] }}"
        uid: "{{ usuarios['everis_prueba']['identificador'] }}"
        expires: "{{ usuarios['everis_prueba']['expira'] }}"

    - name: "Creacion usuario dchico"
      user:
        name: dchico            
        groups: "{{ usuarios['dchico']['grupo'] }}"   
        generate_ssh_key: "{{ usuarios['dchico']['generar_key'] }}"
        ssh_key_bits: 2048
        ssh_key_file: "{{ usuarios['dchico']['ruta_key'] }}"        
        expires: "{{ usuarios['dchico']['expira'] }}"

    - name: "Reiniciar los servicios"
      systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ servicios }}"
    
    - name: "Reiniciar los nodos"
      reboot:
...


